// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelWeb.Areas.Itinerary.Models.ItineraryDBContext;

public partial class Aianalysis
{
    public int AnalysisId { get; set; }

    public int VersionId { get; set; }

    public decimal? FeasibilityScore { get; set; }

    public decimal? PaceBalanceScore { get; set; }

    public decimal? FatigueIndex { get; set; }

    public DateTime? AnalysisTime { get; set; }

    public virtual ItineraryVersion Version { get; set; }
}